version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/nest_auth?schema=public
      JWT_ACCESS_SECRET: super-secret-access
      JWT_REFRESH_SECRET: super-secret-refresh
      JWT_ACCESS_TTL: 15m
      JWT_REFRESH_TTL: 7d
    ports:
      - "3000:3000"

volumes:
  pgdata:
